services:

  db:
    image: mysql:8.4

    container_name: hotel-management-db

    restart: unless-stopped

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/HotelManagementDB.sql:/docker-entrypoint-initdb.d/HotelManagementDB.sql:ro

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-p${MYSQL_ROOT_PASSWORD}"
        ]
      interval: 10s
      timeout: 5s
      retries: 10


  backend:
    build:
      context: ./backend

    container_name: hotel-management-backend

    restart: unless-stopped

    depends_on:
      db:
        condition: service_healthy

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

    ports:
      - "8080:8080"


  frontend:
    build:
      context: ./frontend

    container_name: hotel-management-frontend

    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "3000:80"


volumes:

  mysql_data: